### ISSUE TITLE
Compatibility issue with Python 3.9

### ISSUE THREAD

**Issue by rwielinga** [mjhea0/flask-basic-registration#2]
coverage and alembic need to be updated to recent versions for the application to work:

alembic==1.5.5
coverage==5.4

Tests ran successfully using these versions.

**Comment by mjhea0** [comment]
Thanks. @rwielinga! Do you want to submit a quick PR?

**Comment by mjhea0** [comment]
https://github.com/mjhea0/flask-basic-registration/pull/3
